import { AdvancedNewsType, NormalNewsType } from '.'

export const Data: (NormalNewsType | AdvancedNewsType)[] = [
  {
    title: '这些重大问题，习近平的回答掷地有声',
    top: true,
    medium: '新华社新媒体',
    newsUrl: '',
    type: 'normal',
  },
  {
    title: '这些重大问题，习近平的回答掷地有声',
    top: true,
    medium: '新华社新媒体',
    newsUrl: '',
    type: 'normal',
  },
  {
    title: '蔡英文财产曝光：存款5406万，名下拥有6笔不动产',
    hotSpot: true,
    commnetNum: 120,
    newsUrl: '../../asset/avatar.jpg',
    medium: '人民日报海外网',
    type: 'advanced',
  },
  {
    title: '蔡英文财产曝光：存款5406万，名下拥有6笔不动产',
    hotSpot: true,
    commnetNum: 120,
    newsUrl: '../../asset/avatar.jpg',
    medium: '人民日报海外网',
    type: 'advanced',
  },
  {
    title: '蔡英文财产曝光：存款5406万，名下拥有6笔不动产',
    hotSpot: true,
    commnetNum: 120,
    newsUrl: '../../asset/avatar.jpg',
    medium: '人民日报海外网',
    type: 'advanced',
  },
  {
    title: '蔡英文财产曝光：存款5406万，名下拥有6笔不动产',
    hotSpot: true,
    commnetNum: 120,
    newsUrl: '../../asset/avatar.jpg',
    medium: '人民日报海外网',
    type: 'advanced',
  },
  {
    title: '蔡英文财产曝光：存款5406万，名下拥有6笔不动产',
    hotSpot: true,
    commnetNum: 120,
    newsUrl: '../../asset/avatar.jpg',
    medium: '人民日报海外网',
    type: 'advanced',
  },
  {
    title: '蔡英文财产曝光：存款5406万，名下拥有6笔不动产',
    hotSpot: true,
    commnetNum: 120,
    newsUrl: '../../asset/avatar.jpg',
    medium: '人民日报海外网',
    type: 'advanced',
  },
  {
    title: '蔡英文财产曝光：存款5406万，名下拥有6笔不动产',
    hotSpot: true,
    commnetNum: 120,
    newsUrl: '../../asset/avatar.jpg',
    medium: '人民日报海外网',
    type: 'advanced',
  },
]
